name: talk
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  intl_phone_field: ^3.2.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  firebase_core: ^3.5.0
  google_fonts: ^6.3.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  fluttertoast: ^8.2.8
  firebase_storage: ^12.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_sticky_widgets: ^0.0.3
  firebase_app_check: ^0.3.2+10
  intl: ^0.20.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/homepics/
    - assets/images/services/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
